import { Inter } from 'next/font/google'

import Providers from '../providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Microlink Query Language (MQL)',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className} style={{ margin: 0 }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
